---

- name: Prep Ubuntu
  hosts: all
  become: yes
  tasks:
  - import_tasks: update-hosts.yaml
  - import_tasks: update-ubuntu.yaml
  - import_tasks: install-pkgs.yaml

- name: Setup Jumpbox
  hosts: desktop
  become: yes
  tasks:
  - import_tasks: install-desktop.yaml

